#!/usr/bin/env bash

set -e
set -u
set -o pipefail
set -x

SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
SIMD_DIR=$(realpath ${SCRIPT_DIR}/../../../simapp/simd)
cd ${SIMD_DIR}
go install
# simd start --log_level=debug --log_format=json | grep --line-buffered -E '^{' | jq -r -c --unbuffered '. | select(.module == "x/mev") | del(.level, .ts)'
simd start --log_level=debug --log_format=json | grep --line-buffered -E '^{' | jq -r -c --unbuffered '. | del(.level, .ts)'
